manifest:
  defaults:
    revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: inogai
      url-base: https://github.com/inogai
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
    - name: zmk-feature-appcompanion
      remote: inogai
      revision: main
  self:
    path: config
